spring.application.name=chatbotwa

# Configuración del servidor
server.port=8080

# Credenciales de WhatsApp Cloud API
whatsapp.verify-token=mi_token_super_secreto
whatsapp.api-token=aqui_ira_el_token_permanente_de_meta
whatsapp.phone-number-id=aqui_ira_el_id_del_numero

# Credenciales de Google Gemini
spring.ai.gemini.api-key=AIzaSyAnVkQzusMEMMvgdPQIW8fugyOfZsFsnTs
spring.ai.gemini.chat.options.model=gemini-2.0-flash
